#!/usr/bin/env node
// ONE-OFF (#647): wrote the token data of `projects/tokens/src` from the Helix preset that helix-core resolves
// (Aura base merged with the Helix overrides and the muted palettes). Kept for reference and to prove where the
// data came from; the data is the source now, change it there. It needs `dist/core` and goes away with helix-core
// (epic #585).
//
// Writes: types.ts, primitive.ts, semantic.ts, components/<name>.ts, components/index.ts, index.ts,
// tailwind.ts (the unmuted Tailwind scales the palette generator reads). `palettes.ts` is generated by
// scripts/helix-palettes.mjs. Format the result with `npx biome format --write projects/tokens`.
//
// Run: node scripts/tokens/extract-preset.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPreset } from '../export-tokens.mjs';
import { auraPrimitive, SCALES } from '../helix-palettes.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.join(ROOT, 'projects/tokens/src');
const CORE_AURA = path.join(ROOT, 'projects/core/themes/aura/base/index.ts');

const isIdent = (k) => /^[A-Za-z_$][\w$]*$/.test(k) || /^\d+$/.test(k);
const quote = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

/** A TypeScript object literal; `raw(key, value)` may return source text to emit instead of the value. */
function literal(value, indent = 0, raw = () => undefined) {
  const pad = '  '.repeat(indent + 1);
  const entries = Object.entries(value).map(([k, v]) => {
    const key = isIdent(k) ? k : quote(k);
    const text =
      raw(k, v, indent) ??
      (v !== null && typeof v === 'object' ? literal(v, indent + 1, raw) : quote(v));
    return `${pad}${key}: ${text},`;
  });
  return `{\n${entries.join('\n')}\n${'  '.repeat(indent)}}`;
}

const write = (file, text) => {
  fs.mkdirSync(path.dirname(path.join(OUT, file)), { recursive: true });
  fs.writeFileSync(path.join(OUT, file), text);
};

const header = (what) =>
  `// ${what}\n// Extracted once from the Helix preset of helix-core (scripts/tokens/extract-preset.mjs); this file is the source now.\n`;

const { preset } = await loadPreset('helix');

write(
  'types.ts',
  `// The shape of every token module: nested records whose leaves are CSS values or \`{path}\` references to
// other tokens (\`{primary.600}\`). Data only: no functions, no imports of any styling engine.
export interface TokenTree {
  [key: string]: string | number | TokenTree;
}
`,
);

// primitive: Aura's key order matters (it is the order of the CSS); the muted scales are `palettes.<name>`,
// generated by scripts/helix-palettes.mjs from tailwind.ts (checked against the preset by the tokens test)
const raw = (key, _value, indent) => (indent === 0 && SCALES.includes(key) ? `palettes.${key}` : undefined);
write(
  'primitive.ts',
  `${header('Primitive tokens: the radii, the Helix colour scales (muted, see palettes.ts) and the neutral scales.')}import { palettes } from './palettes.ts';
import type { TokenTree } from './types.ts';

export const primitive = ${literal(preset.primitive, 0, raw)} satisfies TokenTree;
`,
);

write(
  'semantic.ts',
  `${header('Semantic tokens: what the primitives mean (primary, surface, text, form field, overlay …), with the light and dark colour schemes.')}import type { TokenTree } from './types.ts';

export const semantic = ${literal(preset.semantic)} satisfies TokenTree;
`,
);

const names = Object.keys(preset.components);
for (const name of names) {
  write(
    `components/${name}.ts`,
    `${header(`Component tokens of "${name}".`)}import type { TokenTree } from '../types.ts';

export const ${name} = ${literal(preset.components[name])} satisfies TokenTree;
`,
  );
}
write(
  'components/index.ts',
  `${header('Every component token set of the Helix preset, in the order of the preset.')}${names
    .map((n) => `import { ${n} } from './${n}.ts';`)
    .join('\n')}

export const components = {
${names.map((n) => `  ${n},`).join('\n')}
};
`,
);

write(
  'index.ts',
  `${header('The Helix design tokens as data: the input of the token resolver.')}import { components } from './components/index.ts';
import { palettes } from './palettes.ts';
import { primitive } from './primitive.ts';
import { semantic } from './semantic.ts';
import type { TokenTree } from './types.ts';

export type { TokenTree };
export { palettes };

/** The preset: primitive, semantic and component layers. */
export const helixTokens = { primitive, semantic, components };
`,
);

// the unmuted Tailwind scales, input of scripts/helix-palettes.mjs
const aura = auraPrimitive(fs.readFileSync(CORE_AURA, 'utf8'));
write(
  'tailwind.ts',
  `${header("Tailwind CSS's colour scales (MIT, Tailwind Labs) that the palette generator mutes: the input of scripts/helix-palettes.mjs.")}import type { TokenTree } from './types.ts';

export const tailwind = {
${SCALES.map((n) => `  ${n}: { ${Object.entries(aura[n]).map(([k, v]) => `${k}: '${v}'`).join(', ')} },`).join('\n')}
} satisfies Record<string, TokenTree>;
`,
);

console.log(`wrote ${names.length} component sets, primitive, semantic, tailwind to ${path.relative(ROOT, OUT)}`);
