import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-documentation',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="card">
      <div class="font-semibold text-2xl mb-2">Documentation</div>
      <div class="font-semibold text-xl mb-2">Get Started</div>
      <p class="text-lg mb-2">
        Helix is an Angular UI component ecosystem by Gravion Labs — a maintained fork of PrimeNG
        21.1.9 rebranded with <i>h-</i> selectors, plus an application shell, form utilities, and
        AG Grid helpers built on top of it.
      </p>
      <pre class="app-code"><code>npm install &#64;helix-ui/core</code></pre>
      <p class="text-lg mb-2">
        This demo app (<i>apps/helix-demo</i>) is a monorepo workspace app used to develop and
        showcase the libraries below. To run it locally, clone the repo and use pnpm:
      </p>
      <pre class="app-code"><code>pnpm install
pnpm start</code></pre>

      <div class="font-semibold text-xl mb-2">Packages</div>
      <ul class="leading-normal list-disc pl-8 text-lg mb-2">
        <li>
          <span class="text-primary font-medium">&#64;helix-ui/core</span>: Base component
          library — the vendored PrimeNG fork, one secondary entry point per component
          (<i>&#64;helix-ui/core/button</i>).
        </li>
        <li>
          <span class="text-primary font-medium">&#64;helix-ui/shell</span>: Application shell —
          layout (topbar, nav rail, footer), auth pages, landing widgets, and the layout signal
          store.
        </li>
        <li>
          <span class="text-primary font-medium">&#64;helix-ui/zod</span>: Zod v4 adapter —
          reactive-forms validator bridge and dynamic forms from annotated Zod schemas.
        </li>
        <li>
          <span class="text-primary font-medium">&#64;helix-ui/ag-grid</span>: AG Grid helpers —
          value formatters, number parsers, and cell styles.
        </li>
      </ul>

      <div class="font-semibold text-xl mb-2">Structure</div>
      <p class="text-lg mb-2">
        This app's source under <i>src/app</i> is organized as follows:
      </p>
      <ul class="leading-normal list-disc pl-8 text-lg mb-2">
        <li>
          <span class="text-primary font-medium">src/app/shell</span>: Demo-specific shell wiring
          — the menu model and the app shell component.
        </li>
        <li>
          <span class="text-primary font-medium">src/app/pages</span>: Demo content — Dashboard,
          UI Components showcase (<i>uikit</i>), CRUD sample, and this Documentation page.
        </li>
        <li>
          <span class="text-primary font-medium">public/source</span>: Raw source snippets shown
          alongside each UI Components demo, generated by
          <i>scripts/generate-source-assets.mjs</i>.
        </li>
      </ul>

      <div class="font-semibold text-xl mb-2">Menu</div>
      <p class="text-lg mb-2">
        The main navigation menu is defined in
        <span class="bg-highlight px-2 py-1 rounded-border not-italic text-base"
          >src/app/shell/menu.model.ts</span
        >. Update <i>DEMO_MENU_MODEL</i> to add or rearrange menu items.
      </p>

      <div class="font-semibold text-xl mb-2">Layout Store</div>
      <p class="text-lg mb-2">
        The layout state (dark mode, theme preset, menu mode) is managed by
        <span class="bg-highlight px-2 py-1 rounded-border not-italic text-base">LayoutStore</span
        >, an NgRx Signal Store exported from <i>&#64;helix-ui/shell</i>.
      </p>

      <div class="font-semibold text-xl mb-2">Tailwind CSS</div>
      <p class="text-lg mb-2">
        The demo pages are developed with Tailwind CSS, while the application shell itself ships
        its own pre-built stylesheet.
      </p>

      <div class="font-semibold text-xl mb-2">More docs</div>
      <p class="text-lg mb-2">
        Full API references live in the repository under <i>docs/</i> — one page per
        <i>&#64;helix-ui/core</i> module, plus the <i>&#64;helix-ui/shell</i> API reference and
        project roadmap.
      </p>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.Eager,
})
export class Documentation {}
