#!/usr/bin/env node
// The CSS of @gravionlabs/helix-ui (#541): dist/ui/styles.css and dist/ui/tokens.css.
//
//   styles.css  projects/ui/styles/*.scss (compiled to plain CSS), one file per component, in a `components` cascade layer:
//               an application's unlayered CSS and Tailwind's `utilities` layer win over it, so a
//               component can be adjusted from the outside without specificity fights.
//   tokens.css  the Helix tokens the components read, resolved from helixPreset with the engine of
//               helix-core: the primitive/semantic/global variables and the tokens of every
//               component that has a stylesheet (light on :root, dark under `.app-dark`). Load it in
//               every app: the helix-core engine emits a component's tokens only once a core component of
//               that kind is on the page, so a ui Button next to no core `h-button` would find none.
//
// Run: node scripts/build-ui-css.mjs   (needs nothing built: the tokens are resolved from projects/tokens)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as sass from 'sass';
import { helixTokens } from '../projects/tokens/src/index.ts';
import { DARK_SELECTOR } from './export-tokens.mjs';
import { resolveTokens } from './tokens/resolve.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const STYLES = path.join(ROOT, 'projects/ui/styles');
export const OUT = path.join(ROOT, 'dist/ui');

/**
 * The tokens of the preset's components that each stylesheet reads (the stylesheet `input.scss` reads those of
 * `inputtext`, …). A stylesheet without an entry here is an error, so a new component cannot ship without its tokens.
 */
export const TOKEN_COMPONENTS = {
  accordion: ['accordion'],
  breadcrumb: ['breadcrumb'],
  button: ['button'],
  card: ['card'],
  checkbox: ['checkbox'],
  divider: ['divider'],
  'float-label': ['floatlabel'],
  fieldset: ['fieldset'],
  'icon-field': ['iconfield', 'inputtext'],
  input: ['inputtext', 'textarea'],
  listbox: ['listbox', 'inputtext'],
  message: ['message'],
  'multi-select': ['multiselect', 'inputtext', 'checkbox'],
  'auto-complete': ['autocomplete', 'inputtext'],
  'date-picker': ['datepicker', 'inputtext'],
  'file-upload': ['fileupload', 'button'],
  'input-group': ['inputgroup'],
  'input-number': ['inputnumber', 'inputtext'],
  panel: ['panel'],
  password: ['password', 'inputtext'],
  radio: ['radiobutton'],
  select: ['select'],
  slider: ['slider'],
  rating: ['rating'],
  'select-button': ['selectbutton', 'togglebutton'],
  'cdk-overlay': [],
  switch: ['toggleswitch'],
  'toggle-button': ['togglebutton'],
  toolbar: ['toolbar'],
  tooltip: ['tooltip'],
};

/** The component stylesheets, `{ name: 'button', css }`, in name order. */
export function componentStyles(dir = STYLES) {
  const own = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.scss') && !f.startsWith('_'))
    .sort()
    .map((f) => ({
      name: f.slice(0, -5),
      // SCSS is a build-time convenience (loops, mixins, nesting): the package ships plain CSS
      css: sass.compile(path.join(dir, f), { style: 'expanded' }).css.trim(),
    }));
  // The CDK overlay container's structural CSS (positioning, z-index, backdrop) comes first: overlay based
  // components (Select, …) do not work without it.
  const cdk = path.join(ROOT, 'node_modules/@angular/cdk/overlay-prebuilt.css');
  return [{ name: 'cdk-overlay', css: fs.readFileSync(cdk, 'utf8').trim() }, ...own];
}

export function buildStyles(styles = componentStyles()) {
  const body = styles.map(({ name, css }) => `/* ${name} */\n${css}`).join('\n\n');
  const indented = body
    .split('\n')
    .map((line) => (line ? `  ${line}` : line))
    .join('\n');
  return `/* @gravionlabs/helix-ui: generated by scripts/build-ui-css.mjs from projects/ui/styles (do not edit). */\n/* The layer order Tailwind uses, stated here so it holds whichever stylesheet loads first. */\n@layer theme, base, components, utilities;\n\n@layer components {\n${indented}\n}\n`;
}

export function buildTokens(styles = componentStyles()) {
  const components = [
    ...new Set(
      styles.flatMap((s) => {
        const tokens = TOKEN_COMPONENTS[s.name];
        if (!tokens) throw new Error(`projects/ui/styles/${s.name}.scss has no entry in TOKEN_COMPONENTS (scripts/build-ui-css.mjs)`);
        return tokens;
      }),
    ),
  ];
  const { css } = resolveTokens(helixTokens, { darkSelector: DARK_SELECTOR, components });
  return `/* @gravionlabs/helix-ui: the Helix tokens the components read, from helixPreset (generated by scripts/build-ui-css.mjs; do not edit). Light on :root, dark under ${DARK_SELECTOR}. */\n${css}\n`;
}

/** `var(--h-x)` used without a fallback that a tokens stylesheet does not define. */
export function undefinedVariables(styles, tokens) {
  const defined = new Set([...tokens.matchAll(/(--h-[\w-]+)\s*:/g)].map((m) => m[1]));
  const used = new Set([...styles.matchAll(/var\((--h-[\w-]+)\)/g)].map((m) => m[1]));
  return [...used].filter((v) => !defined.has(v)).sort();
}

/** Adds `./styles.css` and `./tokens.css` to the exports map of dist/ui (ng-packagr knows only the TS entry). */
export function addCssExports(dist = OUT) {
  const file = path.join(dist, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(file, 'utf8'));
  pkg.exports ??= {};
  for (const name of ['styles.css', 'tokens.css']) pkg.exports[`./${name}`] = `./${name}`;
  fs.writeFileSync(file, `${JSON.stringify(pkg, null, 2)}\n`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const styles = componentStyles();
  const stylesCss = buildStyles(styles);
  const tokensCss = buildTokens(styles);
  const missing = undefinedVariables(stylesCss, tokensCss);
  if (missing.length) {
    console.error(`styles.css uses tokens that tokens.css does not define: ${missing.join(', ')}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, 'styles.css'), stylesCss);
  fs.writeFileSync(path.join(OUT, 'tokens.css'), tokensCss);
  if (fs.existsSync(path.join(OUT, 'package.json'))) addCssExports(OUT);
  console.log(
    `dist/ui: styles.css ${(stylesCss.length / 1024).toFixed(1)} kB (${styles.length} components), tokens.css ${(tokensCss.length / 1024).toFixed(1)} kB`,
  );
}
