// Generated by `node scripts/helix-palettes.mjs` — do not edit by hand.
// Aura's colour scales with their OKLCH chroma × 0.65; lightness and hue unchanged.
import type { PaletteDesignToken } from '@gravionlabs/helix-core/themes/types';

export const palettes = {
    indigo: { 50: '#eff2fb', 100: '#e3e7f7', 200: '#cbd3f0', 300: '#acb6e5', 400: '#8892d7', 500: '#6972c9', 600: '#5359ba', 700: '#464ba3', 800: '#3a3e84', 900: '#33366a', 950: '#1f1f3e' },
    red: { 50: '#fbf3f3', 100: '#f7e5e5', 200: '#f2cfcf', 300: '#e9afaf', 400: '#dd8683', 500: '#d06760', 600: '#be534a', 700: '#9f443c', 800: '#843933', 900: '#6e322e', 950: '#3b1714' },
    green: { 50: '#f3fcf6', 100: '#e4f9eb', 200: '#cbf1d8', 300: '#a6e6bb', 400: '#81d497', 500: '#68bb7a', 600: '#549b63', 700: '#42794f', 800: '#356041', 900: '#2c4f36', 950: '#152b1c' },
    emerald: { 50: '#f0fbf6', 100: '#dcf6e8', 200: '#bdecd5', 300: '#97debf', 400: '#75c9a3', 500: '#60b08b', 600: '#4c8f71', 700: '#3c725c', 800: '#2f5a4a', 900: '#264a3d', 950: '#132a23' },
    yellow: { 50: '#fdfcef', 100: '#fbf8d6', 200: '#f8efb0', 300: '#f2e18b', 400: '#eccf77', 500: '#dab86a', 600: '#b99054', 700: '#92693e', 800: '#785433', 900: '#65452c', 950: '#3a2416' },
    amber: { 50: '#fdfbf1', 100: '#faf3d7', 200: '#f5e7ad', 300: '#efd589', 400: '#eac475', 500: '#dfa865', 600: '#c38451', 700: '#9f613f', 800: '#814c33', 900: '#6a3f2a', 950: '#3c2113' },
    orange: { 50: '#fdf7f1', 100: '#faeede', 200: '#f3dabd', 300: '#ecc095', 400: '#e39f6e', 500: '#dd875a', 600: '#cd714e', 700: '#a9593f', 800: '#864633', 900: '#6c3a2a', 950: '#3a1c14' },
    sky: { 50: '#f3f8fc', 100: '#e5f1f9', 200: '#c7e3f2', 300: '#9bcfea', 400: '#71b9df', 500: '#5ca2ce', 600: '#4883ae', 700: '#38688c', 800: '#305874', 900: '#284960', 950: '#192f3f' },
    blue: { 50: '#f1f6fc', 100: '#e0e9f6', 200: '#c8daf1', 300: '#a4c4e8', 400: '#7aa6dc', 500: '#5a87d0', 600: '#436dc1', 700: '#365aaf', 800: '#2f4a8e', 900: '#2b3f71', 950: '#1d2845' },
    purple: { 50: '#f9f6fc', 100: '#f1eaf9', 200: '#e5d9f4', 300: '#d2bbeb', 400: '#b692df', 500: '#9c6ed1', 600: '#8756c2', 700: '#7346a9', 800: '#623c8b', 900: '#503070', 950: '#351c51' },
} satisfies Record<string, PaletteDesignToken>;
