/**
 * The Helix preset: Helix's own look, expressed as design tokens on top of Aura
 * (ADR 0001, epic #519, mockups of #521). Aura stays the structural base — it is
 * the preset the component styles were written against — and this file holds
 * only what Helix decides differently, in the same three layers the engine
 * resolves:
 *
 * - `primitive`: palettes and radii (Aura's Tailwind-derived scales are kept)
 * - `semantic`: `primary`, `colorScheme.{light,dark}.surface`, text, … — the
 *   choices that give every component the same identity
 * - `components`: per-component overrides, only where the semantic layer isn't enough
 *
 * The look ("Hybrid", round 2 of the mockups, surfaces of proposal D): the neutrals
 * of the sibling sites' VitePress theme, a muted indigo primary and muted severity colours (`palettes.ts`, Tailwind's scales at 55 %
 * chroma), 6 px radius (Aura's `md`), Inter for text and headings and the system
 * monospace for code. Type is not a token of the engine: the font stacks live in
 * `@gravionlabs/helix-shell`'s stylesheet, the font files are the application's
 * (`@fontsource-variable/*`, see the demo's `angular.json`).
 *
 * `scripts/export-tokens.mjs` resolves this preset to static CSS/JSON
 * (`dist/tokens/`) for the docs site, the design-system sync (#522) and the
 * `helix-ui` library (epic #523), so the look is defined once.
 */
import { definePreset } from '@gravionlabs/helix-core/themes';
import { auraPreset } from '@gravionlabs/helix-core/themes/aura';
import type { Preset } from '@gravionlabs/helix-core/themes/types';
import { palettes } from './palettes';

export { palettes as helixPalettes };

/**
 * The neutral scale of both colour schemes: the surfaces and greys of the stock VitePress theme (the look of
 * the other Gravion Labs sites), as one monotone scale. Light uses 0 (page, cards), 50 (chrome), 100 (hover),
 * 200 (dividers), 300 (control borders), 500 (muted text), 600 (text); dark uses 900 (page), 950 (chrome),
 * 800 (cards), 700 (hover, dividers), 600 (control borders), 400 (muted text).
 */
const surface = {
    0: '#ffffff',
    50: '#f6f6f7',
    100: '#ebebef',
    200: '#e2e2e3',
    300: '#c2c2c4',
    400: '#98989f',
    500: '#67676c',
    600: '#3c3c43',
    700: '#2e2e32',
    800: '#202127',
    900: '#1b1b1f',
    950: '#161618'
};

/** Helix's deviations from Aura. Keep this the only place where Helix's identity is encoded. */
export const helixOverrides: Preset = {
    // The primary and severity scales (indigo, red, green, sky, orange, purple, …)
    // with 45 % less chroma than Tailwind's: same lightness, so every contrast ratio
    // holds, but quieter. Generated by `scripts/helix-palettes.mjs`.
    primitive: palettes,
    semantic: {
        primary: {
            50: '{indigo.50}',
            100: '{indigo.100}',
            200: '{indigo.200}',
            300: '{indigo.300}',
            400: '{indigo.400}',
            500: '{indigo.500}',
            600: '{indigo.600}',
            700: '{indigo.700}',
            800: '{indigo.800}',
            900: '{indigo.900}',
            950: '{indigo.950}'
        },
        colorScheme: {
            light: {
                // One neutral scale in both schemes (Aura: slate by day, zinc by night), so the
                // greys don't shift temperature with the theme.
                surface,
                // indigo-600 on white (7.2:1) instead of Aura's 500.
                primary: {
                    color: '{primary.600}',
                    contrastColor: '#ffffff',
                    hoverColor: '{primary.700}',
                    activeColor: '{primary.800}'
                },
                // Soft near-black text (10.9:1 on white) and a muted step that holds 4.5:1 on the
                // chrome and hover surfaces too (surface-500: 5.4:1 on white, 4.6:1 on surface-100).
                text: {
                    color: '{surface.600}',
                    hoverColor: '{surface.700}',
                    mutedColor: '{surface.500}',
                    hoverMutedColor: '{surface.600}'
                },
                formField: {
                    color: '{surface.600}',
                    floatLabelFocusColor: '{primary.color}'
                }
            },
            dark: {
                surface,
                primary: {
                    color: '{primary.400}',
                    contrastColor: '{surface.950}',
                    hoverColor: '{primary.300}',
                    activeColor: '{primary.200}'
                },
                // The warm off-white of the sibling sites' dark theme, not part of the scale.
                text: {
                    color: '#dfdfd6',
                    hoverColor: '{surface.50}',
                    mutedColor: '{surface.400}',
                    hoverMutedColor: '{surface.300}'
                },
                formField: {
                    color: '{text.color}'
                }
            }
        }
    },
    // The contrast button is a softer neutral than Aura's near-black / white (surface 800 by day, 200 by night).
    components: {
        button: {
            colorScheme: {
                light: {
                    root: {
                        contrast: {
                            background: '{surface.800}',
                            hoverBackground: '{surface.700}',
                            activeBackground: '{surface.600}',
                            borderColor: '{surface.800}',
                            hoverBorderColor: '{surface.700}',
                            activeBorderColor: '{surface.600}',
                            focusRing: { color: '{surface.800}' }
                        }
                    }
                },
                dark: {
                    root: {
                        contrast: {
                            background: '{surface.200}',
                            hoverBackground: '{surface.300}',
                            activeBackground: '{surface.400}',
                            borderColor: '{surface.200}',
                            hoverBorderColor: '{surface.300}',
                            activeBorderColor: '{surface.400}',
                            focusRing: { color: '{surface.200}' }
                        }
                    }
                }
            }
        }
    }
};

export const helixPreset: Preset = definePreset(auraPreset, helixOverrides);
