name: CI / Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package:
    name: CI/CD
    uses: GravionLabs/ci/.github/workflows/angular-package.yml@main
    with:
      node-version: '24'
      build-command: npm run build:lib
      run-tests: false
      publish-directory: ./dist/helix
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}
