name: CI / Publish

permissions:
  contents: write
  checks: write
  pull-requests: write
  packages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      force-publish:
        description: 'Publish regardless of the current branch'
        type: boolean
        required: false
        default: false
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    name: CI/CD
    uses: GravionLabs/ci/.github/workflows/angular-package.yml@main
    with:
      node-version: '24'
      package-manager: pnpm
      lint-command: pnpm run lint
      artifact-path: dist
      build-command: pnpm run build
      run-tests: true
      test-command: pnpm run test:ci
      coverage-format: cobertura
      publish-directory: ./helix
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}
